Repository FRONT-END-BOOTCAMP-PLUS-3/myking, pull requests merged in 2025-02, with the labels that each got.

#29 사용자 프로필 조회/수정 기능 구현
  app/(anon)/auth/callback/page.tsx
  app/(anon)/auth/page.tsx
  app/(anon)/auth/setNickname/page.styles.ts
  app/(anon)/auth/setNickname/page.tsx
  app/(anon)/myPage/layout.tsx
  app/(anon)/myPage/map/page.styles.ts
  app/(anon)/myPage/map/page.tsx
  app/(anon)/myPage/profile/edit/page.tsx
  app/(anon)/myPage/profile/layout.tsx
  app/(anon)/myPage/profile/myCreated/page.styles.ts
  app/(anon)/myPage/profile/myCreated/page.tsx
  app/(anon)/myPage/profile/myParticipated/page.tsx
  app/(anon)/myPage/profile/page.styles.ts
  app/(anon)/myPage/profile/page.tsx
  app/(anon)/parties/page.styles.ts
  app/api/auth/route.ts
  app/api/parties/myCreated/route.ts
  app/api/parties/participated/route.ts
  app/api/user/edit/route.ts
  app/api/user/route.ts
  app/layout.tsx
  application/states/userStore.ts
  application/usecases/partyLookup/PartyMyCreatedUsecase.ts
  application/usecases/partyLookup/PartyParticipatedUsecase.ts
  application/usecases/partyLookup/dto/PartyMyCreatedDto.ts
  application/usecases/partyLookup/dto/PartyParticipatedDto.ts
  application/usecases/user/CreateUserUsecase.ts
  application/usecases/user/UpdateUserUsecase.ts
  application/usecases/user/dto/UserCreateDto.ts
  application/usecases/user/dto/UserUpdateDto.ts
  components/bottomNav/bottomNav.styles.ts
  components/bottomNav/bottomNav.tsx
  components/user/AuthUtils.ts
  components/user/ProtectedRoutes.tsx
  components/user/partyButton/party.styles.ts
  components/user/partyButton/party.tsx
  components/user/profileImageUploader/ProfileImageUploader.styles.ts
  components/user/profileImageUploader/ProfileImageUploader.tsx
  components/user/profileNavBar/profileNavBar.styles.ts
  components/user/profileNavBar/profileNavBar.tsx
  context/AuthProvider.tsx
  domain/entities/Course.ts
  domain/repositories/CourseRepository.ts
  domain/repositories/MountainRepository.ts
  domain/repositories/PartyRepository.ts
  domain/repositories/UserRepository.ts
  infrastructure/repositories/SbPartyRepository.ts
  infrastructure/repositories/SbUserRepository.ts
  infrastructure/services/SupabaseStorageService.ts
  public/images/home.svg
  public/images/map.png
  public/images/myPage.svg
  public/images/parties.svg
Labels: 기능 구현

#33 파티 삭제 기능 구현, 로딩 스피너 컴포넌트 구현, bottom nav 오류 수정
  app/(anon)/auth/callback/page.tsx
  app/(anon)/auth/page.styles.ts
  app/(anon)/auth/setNickname/page.tsx
  app/(anon)/myPage/profile/edit/page.tsx
  app/(anon)/myPage/profile/myCreated/page.tsx
  app/(anon)/myPage/profile/myParticipated/page.tsx
  app/(anon)/myPage/profile/page.tsx
  app/api/parties/route.ts
  app/layout.tsx
  app/page.tsx
  application/usecases/party/DeletePartyUsecase.ts
  application/usecases/user/UpdateUserUsecase.ts
  components/bottomNav/bottomNav.styles.ts
  components/bottomNav/bottomNav.tsx
  components/loadingSpinner/loadingSpineer.tsx
  domain/repositories/MountainRepository.ts
  domain/repositories/PartyMemberRepository.ts
  domain/repositories/PartyRepository.ts
  domain/repositories/UserRepository.ts
  infrastructure/repositories/SbPartyMemberRepository.ts
  infrastructure/repositories/SbPartyRepository.ts
  infrastructure/repositories/SbUserRepository.ts
  package-lock.json
  package.json
Labels: 기능 구현

#35 로딩 페이지, 404페이지 구현
  app/admin/mountain/page.tsx
  app/api/admin/course/route.ts
  app/loading.tsx
  app/not-found.tsx
  infrastructure/services/SupabaseStorageService.ts
Labels: 마크업/스타일링

#36 파티 멤버 삭제 기능 구현
  app/(anon)/myPage/profile/myCreated/page.tsx
  app/(anon)/myPage/profile/myParticipated/page.tsx
  app/(anon)/myPage/profile/page.styles.ts
  app/(anon)/myPage/profile/page.tsx
  app/api/myPage/profile/edit/route.ts
  app/api/myPage/profile/myCreated/route.ts
  app/api/myPage/profile/myParticipated/route.ts
  app/api/myPage/profile/route.ts
  app/api/parties/participated/route.ts
  app/api/parties/route.ts
  application/usecases/PartyMember/DeletePartyMemberUsecase.ts
  application/usecases/PartyMember/dto/PartyMemberDeleteDto.ts
  application/usecases/party/DfPartyCreateUsecase.ts
  application/usecases/partyLookup/FindUuidByKakaoUsecase.ts
  domain/repositories/PartyMemberRepository.ts
  infrastructure/repositories/SbPartyMemberRepository.ts
Labels: 기능 구현

#37 관리자 코스 생성, 수정 시 popularity 삭제
  app/admin/course/[courseId]/edit/page.tsx
  app/admin/course/create/page.tsx
  app/admin/course/page.tsx
  app/api/admin/course/create/route.ts
  application/usecases/admin/course/CreateCourseUsecase.ts
  application/usecases/admin/course/FindCourseDetailUsecase.ts
  application/usecases/admin/course/UpdateCourseUsecase.ts
  application/usecases/admin/course/dto/CourseCreateDto.ts
  application/usecases/admin/course/dto/CourseDetailDto.ts
  application/usecases/admin/course/dto/CourseListDto.ts
  application/usecases/admin/course/dto/CourseUpdateDto.ts
  infrastructure/repositories/SbCourseRepository.ts
Labels: 기능 구현

#42 관리자 페이지 레이아웃 수정
  app/admin/course/create/page.tsx
  app/admin/course/page.tsx
  app/admin/layout.styles.ts
  app/admin/mountain/page.styles.ts
  app/admin/user/page.tsx
  app/api/admin/course/[courseId]/edit/route.ts
  components/admin/Sidebar.tsx
Labels: 마크업/스타일링

#43 헤더, 필터 수정
  app/(anon)/parties/[partyId]/page.styles.ts
  app/(anon)/parties/[partyId]/page.tsx
  app/(anon)/parties/create/layout.tsx
  app/(anon)/parties/create/page.styles.ts
  app/(anon)/parties/layout.tsx
  app/(anon)/parties/page.styles.ts
  app/(anon)/parties/page.tsx
  components/header/header.style.ts
  components/party/filter/Filter.styles.ts
  components/party/filter/Filter.tsx
  infrastructure/repositories/SbPartyRepository.ts
Labels: 기능 구현, 마크업/스타일링
